/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Amongus(props) {
  const { nodes, materials } = useGLTF("models/amongus.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.piernas.geometry}
        material={materials["Material Rojo"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.cristal.geometry}
        material={materials.Cristal}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mochila.geometry}
        material={materials["Material Rojo"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials.Birrete}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.amongos_cuerpo_copia.geometry}
        material={materials["Material Rojo"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.gorro.geometry}
        material={materials.Birrete}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.boton.geometry}
        material={materials.Botton}
      />
    </group>
  );
}

useGLTF.preload("models/amongus.glb");